// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXSZ9LWJfy1lnHDPnOwWgcpAUfF7qUFQw',
    appId: '1:787585684695:web:58bcd90182df69a0e70c92',
    messagingSenderId: '787585684695',
    projectId: 'vision-bus',
    authDomain: 'vision-bus.firebaseapp.com',
    storageBucket: 'vision-bus.appspot.com',
    measurementId: 'G-KR3QTLV7XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChbIlmm3Aj8wd9tFZYl8mGhLPUkv_P15I',
    appId: '1:787585684695:android:4748aaad95ba1360e70c92',
    messagingSenderId: '787585684695',
    projectId: 'vision-bus',
    storageBucket: 'vision-bus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy6Knvsn1JVjllQpMYRTa-twHppjIuvGY',
    appId: '1:787585684695:ios:7a98387b1a9ca7d2e70c92',
    messagingSenderId: '787585684695',
    projectId: 'vision-bus',
    storageBucket: 'vision-bus.appspot.com',
    iosClientId: '787585684695-bav1i90jnef4j2tdig58kn3qe6d4tua4.apps.googleusercontent.com',
    iosBundleId: 'com.example.visionBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy6Knvsn1JVjllQpMYRTa-twHppjIuvGY',
    appId: '1:787585684695:ios:7a98387b1a9ca7d2e70c92',
    messagingSenderId: '787585684695',
    projectId: 'vision-bus',
    storageBucket: 'vision-bus.appspot.com',
    iosClientId: '787585684695-bav1i90jnef4j2tdig58kn3qe6d4tua4.apps.googleusercontent.com',
    iosBundleId: 'com.example.visionBus',
  );
}
